name: Unit tests
on:
  push:
     branches:
       - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ["3.11", "3.13"]
    name: clictagger CI ${{ matrix.os }} / ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v6
      # https://github.com/conda-incubator/setup-miniconda
      - uses: conda-incubator/setup-miniconda@26edbf943b735d99317800282664c1ab4025e686
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: clictagger
          environment-file: ${{ matrix.os == 'windows-latest' && 'environment-windows.yml' || 'environment.yml' }}
      - name: Install clictagger via conda
        run: |
          conda run -n clictagger -v pip install -r dev-requirements.txt
      - name: Tests
        run: |
          conda run -n clictagger pytest clictagger tests
      - name: Lint
        run: |
          conda run -n clictagger make lint
        if: ${{ matrix.os == 'ubuntu-latest' }}
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
#        if: ${{ failure() }}
